AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Proof of concept for Spring Boot REST API + CRUD PostgreSQL in AWS Lambda

Globals:
  Api:
    # API Gateway regional endpoints
    EndpointConfiguration: REGIONAL

Resources:
  SubscribersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.egorza.spring.rest.crud.lambda.StreamLambdaHandler::handleRequest
      Runtime: java11
      CodeUri: .
      MemorySize: 1512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 60
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            TimeoutInMillis: 20000
            PayloadFormatVersion: '1.0'
      VpcConfig:
        SecurityGroupIds:
          - sg-06b1270b60ade5add
        SubnetIds:
          - subnet-03f06faa6a76dfed6
          - subnet-07c0faeda54f57ec8
          - subnet-021d7187432bec909

Outputs:
  SubscribersApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/subscribers'
    Export:
      Name: SubscribersApi